services:
  api:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      backend:
        ipv4_address: 172.20.0.2
  mysql:
    image: mysql:5.7
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ex_text
      MYSQL_INITDB_SCRIPT: /api/Model/export_user.sql
    volumes:
      - ./init.sql:/api/Model/export_user.sql
    networks:
      backend:
        ipv4_address: 172.20.0.3
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_PASSWORD: root
      PMA_USER: root
      PMA_HOSTS: mysql
    networks:
      backend:
        ipv4_address: 172.20.0.4
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
